apiVersion: v1
kind: Pod
metadata:
  name: api

spec:
  containers:
  - name: api
    image: vishva15/profiler_final:etl
    ports:
         - containerPort: 5000
    imagePullPolicy: Always

  - name: ui
    image: dhiraj30/workload_profiler_ui:frontend_workload
    ports:
         - containerPort: 3000
    imagePullPolicy: Always

  restartPolicy: OnFailure